"""Seed database with realistic trucking companies."""
import json
import secrets
from .connection import get_db

TRUCKING_COMPANIES = [
    # West Coast - Firm (hard to negotiate)
    {
        "name": "Pacific Coast Freight",
        "contact_phone": "+1-310-555-0142",
        "contact_email": "dispatch@pacificcoastfreight.com",
        "service_areas": ["West Coast", "Pacific Northwest", "Southwest"],
        "fleet_info": {"truck_types": ["53ft Dry Van", "Flatbed"], "capacity": 150, "drivers": 120},
        "personality": "firm",
        "base_rate_multiplier": 1.15,
        "min_discount_threshold": 0.05,
        "rating": 4.7,
    },
    {
        "name": "Golden Gate Logistics",
        "contact_phone": "+1-415-555-0198",
        "contact_email": "quotes@goldengatelogistics.com",
        "service_areas": ["West Coast", "Mountain West"],
        "fleet_info": {"truck_types": ["Reefer", "Dry Van"], "capacity": 80, "drivers": 65},
        "personality": "firm",
        "base_rate_multiplier": 1.20,
        "min_discount_threshold": 0.08,
        "rating": 4.8,
    },
    # Midwest - Flexible (negotiable)
    {
        "name": "Midwest Express Logistics",
        "contact_phone": "+1-312-555-0234",
        "contact_email": "sales@midwestexpress.com",
        "service_areas": ["Midwest", "Great Lakes", "Plains"],
        "fleet_info": {"truck_types": ["Dry Van", "Reefer", "Flatbed"], "capacity": 200, "drivers": 175},
        "personality": "flexible",
        "base_rate_multiplier": 1.0,
        "min_discount_threshold": 0.18,
        "rating": 4.3,
    },
    {
        "name": "Heartland Carriers",
        "contact_phone": "+1-816-555-0156",
        "contact_email": "dispatch@heartlandcarriers.com",
        "service_areas": ["Midwest", "South", "Southwest"],
        "fleet_info": {"truck_types": ["Dry Van", "Step Deck"], "capacity": 120, "drivers": 95},
        "personality": "flexible",
        "base_rate_multiplier": 0.95,
        "min_discount_threshold": 0.20,
        "rating": 4.2,
    },
    {
        "name": "Great Plains Transport",
        "contact_phone": "+1-402-555-0187",
        "contact_email": "booking@greatplainstransport.com",
        "service_areas": ["Plains", "Midwest", "Mountain West"],
        "fleet_info": {"truck_types": ["Dry Van", "Grain Hopper"], "capacity": 90, "drivers": 70},
        "personality": "flexible",
        "base_rate_multiplier": 0.98,
        "min_discount_threshold": 0.15,
        "rating": 4.4,
    },
    # Northeast - Premium (high prices, justified)
    {
        "name": "Empire State Haulers",
        "contact_phone": "+1-212-555-0289",
        "contact_email": "enterprise@empirestatehaul.com",
        "service_areas": ["Northeast", "Mid-Atlantic", "New England"],
        "fleet_info": {"truck_types": ["Dry Van", "Liftgate", "Climate Control"], "capacity": 100, "drivers": 85},
        "personality": "premium",
        "base_rate_multiplier": 1.30,
        "min_discount_threshold": 0.10,
        "rating": 4.9,
    },
    {
        "name": "Liberty Freight Solutions",
        "contact_phone": "+1-215-555-0321",
        "contact_email": "priority@libertyfreight.com",
        "service_areas": ["Northeast", "Mid-Atlantic"],
        "fleet_info": {"truck_types": ["Dry Van", "Reefer", "Expedited"], "capacity": 75, "drivers": 60},
        "personality": "premium",
        "base_rate_multiplier": 1.25,
        "min_discount_threshold": 0.08,
        "rating": 4.8,
    },
    # Southeast - Desperate (need business)
    {
        "name": "Dixie Land Trucking",
        "contact_phone": "+1-404-555-0432",
        "contact_email": "loads@dixielandtrucking.com",
        "service_areas": ["Southeast", "South", "Gulf Coast"],
        "fleet_info": {"truck_types": ["Dry Van", "Flatbed"], "capacity": 60, "drivers": 45},
        "personality": "desperate",
        "base_rate_multiplier": 0.85,
        "min_discount_threshold": 0.35,
        "rating": 3.8,
    },
    {
        "name": "Magnolia Express",
        "contact_phone": "+1-601-555-0543",
        "contact_email": "dispatch@magnoliaexpress.com",
        "service_areas": ["Southeast", "Gulf Coast", "South"],
        "fleet_info": {"truck_types": ["Dry Van"], "capacity": 40, "drivers": 32},
        "personality": "desperate",
        "base_rate_multiplier": 0.80,
        "min_discount_threshold": 0.40,
        "rating": 3.6,
    },
    {
        "name": "Peach State Logistics",
        "contact_phone": "+1-770-555-0654",
        "contact_email": "sales@peachstatelogistics.com",
        "service_areas": ["Southeast", "Mid-Atlantic", "South"],
        "fleet_info": {"truck_types": ["Dry Van", "Reefer"], "capacity": 55, "drivers": 42},
        "personality": "desperate",
        "base_rate_multiplier": 0.88,
        "min_discount_threshold": 0.32,
        "rating": 3.9,
    },
    # Nationwide - Mixed
    {
        "name": "CrossCountry Transport",
        "contact_phone": "+1-800-555-0765",
        "contact_email": "nationwide@crosscountrytrans.com",
        "service_areas": ["Nationwide", "Cross-Border (Canada)", "Cross-Border (Mexico)"],
        "fleet_info": {"truck_types": ["Dry Van", "Reefer", "Flatbed", "Tanker"], "capacity": 500, "drivers": 420},
        "personality": "flexible",
        "base_rate_multiplier": 1.05,
        "min_discount_threshold": 0.15,
        "rating": 4.5,
    },
    {
        "name": "American Highway Carriers",
        "contact_phone": "+1-800-555-0876",
        "contact_email": "dispatch@americanhighway.com",
        "service_areas": ["Nationwide"],
        "fleet_info": {"truck_types": ["Dry Van", "Reefer", "Flatbed"], "capacity": 350, "drivers": 280},
        "personality": "firm",
        "base_rate_multiplier": 1.12,
        "min_discount_threshold": 0.07,
        "rating": 4.6,
    },
    {
        "name": "Interstate Freight Lines",
        "contact_phone": "+1-800-555-0987",
        "contact_email": "quotes@interstatefreight.com",
        "service_areas": ["Nationwide", "Regional Express"],
        "fleet_info": {"truck_types": ["Dry Van", "LTL", "Expedited"], "capacity": 280, "drivers": 220},
        "personality": "flexible",
        "base_rate_multiplier": 1.02,
        "min_discount_threshold": 0.18,
        "rating": 4.4,
    },
    # Texas/Southwest - Mixed
    {
        "name": "Lone Star Trucking",
        "contact_phone": "+1-214-555-0111",
        "contact_email": "dispatch@lonestartrucking.com",
        "service_areas": ["Southwest", "South", "Mountain West"],
        "fleet_info": {"truck_types": ["Dry Van", "Flatbed", "Step Deck"], "capacity": 180, "drivers": 145},
        "personality": "flexible",
        "base_rate_multiplier": 0.95,
        "min_discount_threshold": 0.20,
        "rating": 4.3,
    },
    {
        "name": "Rio Grande Logistics",
        "contact_phone": "+1-915-555-0222",
        "contact_email": "sales@riograndelogistics.com",
        "service_areas": ["Southwest", "Cross-Border (Mexico)", "West Coast"],
        "fleet_info": {"truck_types": ["Dry Van", "Reefer"], "capacity": 95, "drivers": 75},
        "personality": "desperate",
        "base_rate_multiplier": 0.82,
        "min_discount_threshold": 0.35,
        "rating": 3.7,
    },
    {
        "name": "Desert Express Carriers",
        "contact_phone": "+1-602-555-0333",
        "contact_email": "dispatch@desertexpress.com",
        "service_areas": ["Southwest", "Mountain West", "West Coast"],
        "fleet_info": {"truck_types": ["Dry Van", "Flatbed"], "capacity": 70, "drivers": 55},
        "personality": "flexible",
        "base_rate_multiplier": 0.98,
        "min_discount_threshold": 0.22,
        "rating": 4.1,
    },
    # Specialty/Premium
    {
        "name": "Arctic Cold Chain",
        "contact_phone": "+1-800-555-0444",
        "contact_email": "reefer@arcticcoldchain.com",
        "service_areas": ["Nationwide", "Temperature-Controlled"],
        "fleet_info": {"truck_types": ["Reefer", "Frozen", "Multi-Temp"], "capacity": 120, "drivers": 100},
        "personality": "premium",
        "base_rate_multiplier": 1.35,
        "min_discount_threshold": 0.05,
        "rating": 4.9,
    },
    {
        "name": "HazMat Secure Transport",
        "contact_phone": "+1-800-555-0555",
        "contact_email": "hazmat@securetrans.com",
        "service_areas": ["Nationwide", "Hazardous Materials"],
        "fleet_info": {"truck_types": ["Tanker", "HazMat Certified", "Dry Van"], "capacity": 60, "drivers": 50},
        "personality": "premium",
        "base_rate_multiplier": 1.45,
        "min_discount_threshold": 0.03,
        "rating": 4.9,
    },
    {
        "name": "Oversized Load Specialists",
        "contact_phone": "+1-800-555-0666",
        "contact_email": "permits@oversizedload.com",
        "service_areas": ["Nationwide", "Oversized/Heavy Haul"],
        "fleet_info": {"truck_types": ["Lowboy", "RGN", "Multi-Axle"], "capacity": 45, "drivers": 38},
        "personality": "firm",
        "base_rate_multiplier": 1.50,
        "min_discount_threshold": 0.05,
        "rating": 4.8,
    },
    # Regional carriers
    {
        "name": "New England Freight Co",
        "contact_phone": "+1-617-555-0777",
        "contact_email": "dispatch@newenglandfreight.com",
        "service_areas": ["New England", "Northeast"],
        "fleet_info": {"truck_types": ["Dry Van", "LTL"], "capacity": 50, "drivers": 40},
        "personality": "firm",
        "base_rate_multiplier": 1.18,
        "min_discount_threshold": 0.08,
        "rating": 4.5,
    },
    {
        "name": "Rocky Mountain Haulers",
        "contact_phone": "+1-303-555-0888",
        "contact_email": "loads@rockymtnhaulers.com",
        "service_areas": ["Mountain West", "Plains", "West Coast"],
        "fleet_info": {"truck_types": ["Dry Van", "Flatbed"], "capacity": 85, "drivers": 68},
        "personality": "flexible",
        "base_rate_multiplier": 1.0,
        "min_discount_threshold": 0.18,
        "rating": 4.2,
    },
    {
        "name": "Carolina Freight Systems",
        "contact_phone": "+1-704-555-0999",
        "contact_email": "quotes@carolinafreight.com",
        "service_areas": ["Southeast", "Mid-Atlantic", "Northeast"],
        "fleet_info": {"truck_types": ["Dry Van", "Reefer"], "capacity": 110, "drivers": 88},
        "personality": "flexible",
        "base_rate_multiplier": 0.97,
        "min_discount_threshold": 0.20,
        "rating": 4.3,
    },
    {
        "name": "Bayou Transport",
        "contact_phone": "+1-504-555-1010",
        "contact_email": "dispatch@bayoutransport.com",
        "service_areas": ["Gulf Coast", "Southeast", "South"],
        "fleet_info": {"truck_types": ["Dry Van", "Tanker"], "capacity": 65, "drivers": 52},
        "personality": "desperate",
        "base_rate_multiplier": 0.83,
        "min_discount_threshold": 0.38,
        "rating": 3.7,
    },
    {
        "name": "Northwest Cascades Trucking",
        "contact_phone": "+1-206-555-1111",
        "contact_email": "loads@nwcascades.com",
        "service_areas": ["Pacific Northwest", "West Coast", "Mountain West"],
        "fleet_info": {"truck_types": ["Dry Van", "Flatbed", "Logging"], "capacity": 75, "drivers": 60},
        "personality": "firm",
        "base_rate_multiplier": 1.15,
        "min_discount_threshold": 0.06,
        "rating": 4.6,
    },
    {
        "name": "Sunshine State Carriers",
        "contact_phone": "+1-305-555-1212",
        "contact_email": "sales@sunshinestatecarriers.com",
        "service_areas": ["Southeast", "Gulf Coast", "Caribbean Gateway"],
        "fleet_info": {"truck_types": ["Dry Van", "Reefer"], "capacity": 95, "drivers": 76},
        "personality": "flexible",
        "base_rate_multiplier": 0.96,
        "min_discount_threshold": 0.22,
        "rating": 4.1,
    },
    # More variety
    {
        "name": "Budget Freight LLC",
        "contact_phone": "+1-800-555-1313",
        "contact_email": "cheap@budgetfreight.com",
        "service_areas": ["Nationwide", "Economy"],
        "fleet_info": {"truck_types": ["Dry Van"], "capacity": 200, "drivers": 160},
        "personality": "desperate",
        "base_rate_multiplier": 0.78,
        "min_discount_threshold": 0.42,
        "rating": 3.5,
    },
    {
        "name": "Express Priority Logistics",
        "contact_phone": "+1-800-555-1414",
        "contact_email": "urgent@expresspriority.com",
        "service_areas": ["Nationwide", "Expedited", "Same-Day"],
        "fleet_info": {"truck_types": ["Sprinter", "Dry Van", "Air Ride"], "capacity": 80, "drivers": 90},
        "personality": "premium",
        "base_rate_multiplier": 1.55,
        "min_discount_threshold": 0.02,
        "rating": 4.9,
    },
    {
        "name": "Family First Trucking",
        "contact_phone": "+1-513-555-1515",
        "contact_email": "dispatch@familyfirsttrucking.com",
        "service_areas": ["Midwest", "Great Lakes"],
        "fleet_info": {"truck_types": ["Dry Van"], "capacity": 35, "drivers": 28},
        "personality": "desperate",
        "base_rate_multiplier": 0.85,
        "min_discount_threshold": 0.30,
        "rating": 4.0,
    },
    {
        "name": "Veterans Hauling Co",
        "contact_phone": "+1-800-555-1616",
        "contact_email": "support@vetshauling.com",
        "service_areas": ["Nationwide"],
        "fleet_info": {"truck_types": ["Dry Van", "Flatbed"], "capacity": 90, "drivers": 85},
        "personality": "flexible",
        "base_rate_multiplier": 0.98,
        "min_discount_threshold": 0.15,
        "rating": 4.6,
    },
    {
        "name": "Tech Logistics Solutions",
        "contact_phone": "+1-408-555-1717",
        "contact_email": "highvalue@techlogistics.com",
        "service_areas": ["West Coast", "Nationwide", "White Glove"],
        "fleet_info": {"truck_types": ["Air Ride", "Climate Control", "GPS Tracked"], "capacity": 40, "drivers": 35},
        "personality": "premium",
        "base_rate_multiplier": 1.40,
        "min_discount_threshold": 0.05,
        "rating": 4.9,
    },
]


async def seed_companies() -> int:
    """Seed trucking companies if table is empty. Returns count of companies."""
    async with get_db() as db:
        cursor = await db.execute("SELECT COUNT(*) FROM companies")
        row = await cursor.fetchone()
        count = row[0] if row else 0

        if count > 0:
            return count

        for company in TRUCKING_COMPANIES:
            company_id = secrets.token_urlsafe(8)
            await db.execute(
                """INSERT INTO companies
                   (id, name, contact_phone, contact_email, service_areas, fleet_info,
                    personality, base_rate_multiplier, min_discount_threshold, rating)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    company_id,
                    company["name"],
                    company["contact_phone"],
                    company["contact_email"],
                    json.dumps(company["service_areas"]),
                    json.dumps(company["fleet_info"]),
                    company["personality"],
                    company["base_rate_multiplier"],
                    company["min_discount_threshold"],
                    company["rating"],
                ),
            )
        await db.commit()
        return len(TRUCKING_COMPANIES)
